# Main configuration file

# Default configuration groups
defaults:
  - data: casp
  - model: dspp
  - training: default
  - _self_  # For overriding with command line arguments

# System settings
device: "cuda"
random_seed: 42

# Hyperparameter tuning configuration
hyperparam_tuning:
  enabled: false  # Set to true to enable Bayesian optimization
  n_trials: 30    # Number of trials to run
  objective_metric: "mae"  # The metric to optimize (do we optimize for calibration or error?)
  minimize: true   # Whether to minimize or maximize the objective
