# Main configuration file

# Default configuration groups
defaults:
  - data: casp
  - model: dspp
  - training: default
  - _self_  # For overriding with command line arguments

# System settings
device: "cuda"
random_seed: 42
